config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
       resources :foster_parent_ratings
     end
  resource :session, only: [:new, :create, :destroy]
   resources :dogs do
     resources :messages
     resources :matchings, only: [:create, :show]
   end
  get 'dogs/:id/past' => 'matchings#past_match'
  get 'users/:id/info' => 'users#info'
  root 'dogs#index'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  has_many :matchings
  has_many :foster_parents, through: :matchings, class_name: 'User'
end

app/models/foster_parent_rating.rb
class FosterParentRating < ActiveRecord::Base
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  belongs_to :foster_parent, class_name: 'User', foreign_key: :foster_parent_id
end

app/models/matching.rb
class Matching < ActiveRecord::Base
  belongs_to :dog
  belongs_to :foster_parent, class_name: 'User', foreign_key: :foster_parent_id

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  belongs_to :foster_parent, class_name: 'User', foreign_key: :foster_parent_id

end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
  has_many :dogs, foreign_key: :owner_id
  has_many :received_ratings, foreign_key: :foster_parent_id, class_name: 'FosterParentRating'
  has_many :given_ratings, foreign_key: :owner_id, class_name: 'FosterParentRating'
  has_many :messages, foreign_key: :owner_id
  has_many :messages, foreign_key: :foster_parent_id
  has_many :matchings, foreign_key: :foster_parent_id
  has_many :foster_dogs, through: :matchings, source: :dogs

  validates :email, presence: true, uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  # before_action :ensure_current_user, only: [:create, :update, :destroy]

  def current_user
    user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def ensure_current_user
    redirect_to new_session_path unless current_user
  end



end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end


  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      redirect_to '/'
    else
      render :new
    end
  end

  def show
    @dog = Dog.find_by(id: params[:id])
    @matching = @dog.matchings.new
  end




private

  def dog_params
    params.require(:dog).permit(:name, :breed, :sex, :zip, :is_neutered, :description, :age_range, :foster_start, :foster_end).merge(owner_id: current_user.id)
  end

end

app/controllers/foster_parent_ratings_controller.rb
class FosterParentRatingsController < ApplicationController
  def create
      @user = User.find(params[:user_id])
    @rating = @user.received_ratings.build(rating_params)
    if @rating.save

      redirect_to "/users/#{@rating.foster_parent_id}"
    else
      render root_path
    end
  end

  private

  def rating_params
    params.require(:foster_parent_rating).permit(:rating, :comment, :foster_parent_id).merge(owner_id: current_user.id)
  end

  end

app/controllers/matchings_controller.rb
class MatchingsController < ApplicationController

  def create
    @dog = Dog.find_by(id: params[:id])
    @matching = Matching.new(match_params)
    if @matching.save
      redirect_to '/'
    else
      render "dogs/#{@dog.id}"
    end
  end

  def past_match
    @dog = Dog.find_by(id: params[:id])
    render :'matchings/past_matches'
  end


  private
    def match_params
      params.require(:matching).permit(:dog_id, :foster_start, :foster_end).merge(foster_parent_id: current_user.id)
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @msg = Message.new
    @dog = Dog.find(params[:dog_id])
  end

  def create
    @dog = Dog.find(params[:dog_id])
    @message = Message.new(msg_params)
    if @message.save
      redirect_to "/dogs/#{@dog.id}"
    else
      render :new
    end
  end

  # def show
  #   @dog = Dog.find_by(id: params[:id])
  #   @msgs = Message.where(:user_id => @userid).order('updated_at DESC')
  # end




private

  def msg_params
    params.require(:message).permit(:title, :content, :owner_id).merge(foster_parent_id: current_user.id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :ensure_current_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @foster_parent_rating = @user.received_ratings.new
  end

  def info
    @user = current_user
    render :'users/info'
  end



  private

  def user_params
    params.require(:user).permit(:username, :password, :email, :zip, :about_me)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/index.html.erb
<%if current_user %>
<h1> Hi <%= current_user.username%> </h1>
<% end %>
<h1>Welcome to Paws BnB !</h1>

<% @dogs.each do |dog| %>
<div>
<%= link_to dog.name, dog_path(dog) %>
</div>
<% end %>





<%= link_to 'post your paw', new_dog_path %>

app/views/dogs/new.html.erb
<%= form_for @dog do |f| %>
<fieldset>
  <legend> Create your paws profile here:</legend>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :breed %>
    <%= f.text_field :breed %>
  </div>

  <div>
    <%= f.label :sex %>
    <%= f.text_field :sex %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :is_your_paw_neutered? %>
    <%= f.text_field :is_neutered %>
  </div>

  <div>
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div>
    <%= f.label :age_range %>
    <%= f.text_field :age_range %>
  </div>

  <div>
    <%= f.label :foster_start %>
    <%= f.date_select :foster_start %>
  </div>

  <div>
    <%= f.label :foster_end %>
    <%= f.date_select :foster_end %>
  </div>


  <div>
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/dogs/show.html.erb
<h1><%=@dog.name %></h1>

<h4>Breed: <%=@dog.breed %> </h4>
<h4>Sex: <%=@dog.sex %></h4>
<h4>Neutered: <%=@dog.is_neutered %></h4>
<h4>Description: <%=@dog.description %></h4>
<h4>Zip: <%=@dog.zip %></h4>
<h4>Age_range: <%=@dog.age_range %></h4>
<h4>Owner: <%= link_to @dog.owner.username, user_path(@dog.owner) %></h4>
<h4>Searching for foster home from: <%=@dog.foster_start %> ~ <%=@dog.foster_end %></h4>


<h3>Want to foster <%=@dog.name %>? <%= link_to "Message #{@dog.owner.username}", new_dog_message_path(@dog) %> </h3>

<%= form_for [@dog, @matching] do |f| %>
  <div>
    <%= f.label :foster_start %>
    <%= f.date_select :foster_start %>
  </div>

  <div>
    <%= f.label :foster_end %>
    <%= f.date_select :foster_end %>
  </div>
  <%= f.hidden_field :dog_id, value: @dog.id %>

  <div>
    <%= f.submit "Foster #{@dog.name}" %>
  </div>


<% end %>


<%= link_to 'Past Host Parents', "/dogs/#{@dog.id}/past" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PawsBnb</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
<% if current_user %>
<%= link_to "log out", session_path, method: :delete %>
<%= link_to 'Main Page', root_path %>
<%= link_to 'Your Page', "users/#{current_user.id}/info"%>
<% else %>
<%= link_to 'Log in', new_session_path %>
<%= link_to 'Register', new_user_path %>
<% end %>
</div>

<%= yield %>

</body>
</html>

app/views/matchings/past_matches.html.erb
<h3>Past Foster Parents of <%=@dog.name %></h3>

<% @dog.matchings.each do |match| %>
<div>
<%= match.foster_start %>
<%= match.foster_end %>
<%= match.foster_parent.username %>
</div>
<% end %>


<%=link_to 'back to paw', dog_path(@dog) %>

app/views/messages/new.html.erb
<%= form_for(@msg, url: dog_messages_path) do |f| %>
<fieldset>
  <legend> Send your message here</legend>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <%= f.hidden_field :owner_id, value: @dog.owner_id %>

  <div>
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/users/info.html.erb
<h1>Hi user</h1>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<fieldset>
  <legend> Please Register Here</legend>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :about_me %>
    <%= f.text_field :about_me %>
  </div>

  <div>
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div>
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/users/show.html.erb
<h1><%=@user.username %></h1>

<%= @user.zip %>
<%= @user.about_me %>


<% if @user.dogs.count != 0 %>
<h3>My Paws</h3>
<% @user.dogs.each do |dog|%>
<h2><%= link_to dog.name, dog_path(dog)%></h2>
<% end  %>
<% end %>



<h3><%=@user.username %>'s ratings:</h3>
<div>
<% @user.received_ratings.each do |rating|%>
<h4> Rating: <%= rating.rating %> </h4>
<h4> Comment: <%= rating.comment %> </h4>
</div>
<% end %>
<hr>




<h2>Rate Host</h2>

<%= form_for [@user, @foster_parent_rating] do |f| %>
  <div>
    <%= f.label :rating %>
    <%= f.select :rating, value: [1,2,3,4,5] %>
  </div>

  <div>
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>
  <%= f.hidden_field :foster_parent_id, value: @user.id %>

  <div>
    <%= f.submit "Submit Rating" %>
  </div>


<% end %>